export const LANGUAGE_TEXT_VIEW_BILL: any = {
  en: {
    invoiceDetails: "Bill Details",
    loadingBill: "Loading bill...",
    totalPayable: "Total Amount",
    issuedOn: "Date",
    customer: "Customer",
    walkIn: "Walk-in Customer",
    noPhone: "No phone number",
    orderSummary: "Items",
    subtotal: "Subtotal",
    discount: "Discount",
    netTotal: "Final Total",
    amountPaid: "Paid Amount",
    balanceDue: "Balance",
    share: "Share Bill",
    print: "Print",
    units: "pcs",
    status: {
      PAID: "Paid",
      PARTIAL: "Part Paid",
      UNPAID: "Due",
    },
  },

  hi: {
    invoiceDetails: "बिल की जानकारी",
    loadingBill: "बिल लोड हो रहा है...",
    totalPayable: "कुल राशि",
    issuedOn: "तारीख",
    customer: "ग्राहक",
    walkIn: "वॉक-इन ग्राहक",
    noPhone: "नंबर उपलब्ध नहीं",
    orderSummary: "सामान",
    subtotal: "कुल जोड़",
    discount: "छूट",
    netTotal: "अंतिम राशि",
    amountPaid: "जमा राशि",
    balanceDue: "बाकी",
    share: "बिल शेयर करें",
    print: "प्रिंट",
    units: "नग",
    status: {
      PAID: "चुकता",
      PARTIAL: "आंशिक",
      UNPAID: "बाकी",
    },
  },

  pa: {
    invoiceDetails: "ਬਿੱਲ ਦੀ ਜਾਣਕਾਰੀ",
    loadingBill: "ਬਿੱਲ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    totalPayable: "ਕੁੱਲ ਰਕਮ",
    issuedOn: "ਤਾਰੀਖ",
    customer: "ਗਾਹਕ",
    walkIn: "ਵਾਕ-ਇਨ ਗਾਹਕ",
    noPhone: "ਨੰਬਰ ਨਹੀਂ",
    orderSummary: "ਸਾਮਾਨ",
    subtotal: "ਜੋੜ",
    discount: "ਛੂਟ",
    netTotal: "ਅੰਤਿਮ ਰਕਮ",
    amountPaid: "ਜਮ੍ਹਾਂ ਰਕਮ",
    balanceDue: "ਬਾਕੀ",
    share: "ਬਿੱਲ ਸਾਂਝਾ ਕਰੋ",
    print: "ਪ੍ਰਿੰਟ",
    units: "ਨਗ",
    status: {
      PAID: "ਅਦਾ",
      PARTIAL: "ਅੱਧਾ ਭੁਗਤਾਨ",
      UNPAID: "ਬਾਕੀ",
    },
  },

  gu: {
    invoiceDetails: "બિલની વિગતો",
    loadingBill: "બિલ લોડ થઈ રહ્યું છે...",
    totalPayable: "કુલ રકમ",
    issuedOn: "તારીખ",
    customer: "ગ્રાહક",
    walkIn: "વોક-ઇન ગ્રાહક",
    noPhone: "નંબર નથી",
    orderSummary: "સામાન",
    subtotal: "કુલ જોડ",
    discount: "છૂટ",
    netTotal: "અંતિમ રકમ",
    amountPaid: "ચૂકવેલ રકમ",
    balanceDue: "બાકી",
    share: "બિલ શેર કરો",
    print: "પ્રિન્ટ",
    units: "નગ",
    status: {
      PAID: "ચુકવેલ",
      PARTIAL: "થોડી ચુકવણી",
      UNPAID: "બાકી",
    },
  },

  mr: {
    invoiceDetails: "बिल माहिती",
    loadingBill: "बिल लोड होत आहे...",
    totalPayable: "एकूण रक्कम",
    issuedOn: "तारीख",
    customer: "ग्राहक",
    walkIn: "वॉक-इन ग्राहक",
    noPhone: "नंबर नाही",
    orderSummary: "सामान",
    subtotal: "एकूण जोड",
    discount: "सूट",
    netTotal: "अंतिम रक्कम",
    amountPaid: "भरलेली रक्कम",
    balanceDue: "बाकी",
    share: "बिल शेअर करा",
    print: "प्रिंट",
    units: "नग",
    status: {
      PAID: "चुकता",
      PARTIAL: "अर्धवट भरले",
      UNPAID: "बाकी",
    },
  },

  te: {
    invoiceDetails: "బిల్ వివరాలు",
    loadingBill: "బిల్ లోడ్ అవుతోంది...",
    totalPayable: "మొత్తం మొత్తం",
    issuedOn: "తేదీ",
    customer: "గ్రాహకుడు",
    walkIn: "వాక్-ఇన్ కస్టమర్",
    noPhone: "నంబర్ లేదు",
    orderSummary: "సరుకులు",
    subtotal: "మొత్తం జోడింపు",
    discount: "తగ్గింపు",
    netTotal: "చివరి మొత్తం",
    amountPaid: "చెల్లించిన మొత్తం",
    balanceDue: "బాకీ",
    share: "బిల్ షేర్ చేయండి",
    print: "ప్రింట్",
    units: "నగ",
    status: {
      PAID: "చెల్లించారు",
      PARTIAL: "కొంత చెల్లించారు",
      UNPAID: "బాకీ",
    },
  },
};
