export const LANGUAGE_TEXT_INVENTORY_HEADER: any = {
  en: {
    title: "Inventory",
    subtitle: "Manage stock & prices easily",
    addProduct: "Add Product",
    quickEntry: "Quick Entry",
    barcodeSheet: "Generate Barcode Sheet",
  },
  hi: {
    title: "स्टॉक / माल",
    subtitle: "सामान और रेट आसानी से मैनेज करें",
    addProduct: "माल जोड़ें",
    quickEntry: "तेज़ एंट्री",
    barcodeSheet: "बारकोड शीट बनाएं",
  },
  pa: {
    title: "ਸਟਾਕ",
    subtitle: "ਸਮਾਨ ਅਤੇ ਰੇਟ ਆਸਾਨੀ ਨਾਲ ਮੈਨੇਜ ਕਰੋ",
    addProduct: "ਸਮਾਨ ਜੋੜੋ",
    quickEntry: "ਤੁਰੰਤ ਐਂਟਰੀ",
    barcodeSheet: "ਬਾਰਕੋਡ ਸ਼ੀਟ ਬਣਾਓ",
  },
  gu: {
    title: "સ્ટોક",
    subtitle: "સામાન અને ભાવ સરળતાથી મેનેજ કરો",
    addProduct: "સામાન ઉમેરો",
    quickEntry: "ઝડપી એન્ટ્રી",
    barcodeSheet: "બારકોડ શીટ બનાવો",
  },
  mr: {
    title: "स्टॉक / माल",
    subtitle: "माल आणि दर सहजपणे व्यवस्थापित करा",
    addProduct: "माल जोडा",
    quickEntry: "झटपट नोंद",
    barcodeSheet: "बारकोड शीट तयार करा",
  },
  te: {
    title: "స్టాక్",
    subtitle: "వస్తువులు మరియు ధరలను సులభంగా నిర్వహించండి",
    addProduct: "వస్తువును జోడించు",
    quickEntry: "త్వరిత ఎంట్రీ",
    barcodeSheet: "బార్‌కోడ్ షీట్‌ను రూపొందించండి",
  },
};

export const LANGUAGE_TEXT_INVENTORY_MENU: any = {
  en: {
    edit: "Edit Product",
    delete: "Delete",
  },
  hi: {
    edit: "बदलाव करें",
    delete: "हटाएं",
  },
  pa: {
    edit: "ਸੋਧੋ",
    delete: "ਹਟਾਓ",
  },
  gu: {
    edit: "ફેરફાર કરો",
    delete: "કાઢી નાખો",
  },
  mr: {
    edit: "बदल करा",
    delete: "काढून टाका",
  },
  te: {
    edit: "సవరించు",
    delete: "తొలగించు",
  },
};

export const LANGUAGE_TEXT_INVENTORY_ROW: any = {
  en: {
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    lowStock: "Low Stock",
    priceLabel: "PRICE",
    stockLabel: "STOCK",
    errorUpdateStock: "Failed to update stock",
    errorUpdatePrice: "Failed to update price",
    deleteTitle: "Delete Product",
    deleteMsg: (name: string) => `Remove ${name}?`,
    cancel: "Cancel",
    delete: "Delete",
  },
  hi: {
    inStock: "स्टॉक में है",
    outOfStock: "खत्म हो गया",
    lowStock: "कम स्टॉक",
    priceLabel: "रेट",
    stockLabel: "स्टॉक",
    errorUpdateStock: "स्टॉक अपडेट नहीं हो पाया",
    errorUpdatePrice: "रेट अपडेट नहीं हो पाया",
    deleteTitle: "सामान हटाएं",
    deleteMsg: (name: string) => `क्या आप ${name} को हटाना चाहते हैं?`,
    cancel: "रद्द करें",
    delete: "हटाएं",
  },
  pa: {
    inStock: "ਸਟਾਕ ਵਿੱਚ ਹੈ",
    outOfStock: "ਖਤਮ ਹੈ",
    lowStock: "ਘੱਟ ਸਟਾਕ",
    priceLabel: "ਰੇਟ",
    stockLabel: "ਸਟਾਕ",
    errorUpdateStock: "ਸਟਾਕ ਅਪਡੇਟ ਨਹੀਂ ਹੋਇਆ",
    errorUpdatePrice: "ਰੇਟ ਅਪਡੇਟ ਨਹੀਂ ਹੋਇਆ",
    deleteTitle: "ਸਾਮਾਨ ਹਟਾਓ",
    deleteMsg: (name: string) => `ਕੀ ਤੁਸੀਂ ${name} ਨੂੰ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?`,
    cancel: "ਰੱਦ ਕਰੋ",
    delete: "ਹਟਾਓ",
  },
  gu: {
    inStock: "સ્ટોક છે",
    outOfStock: "ખલાસ છે",
    lowStock: "ઓછો સ્ટોક",
    priceLabel: "ભાવ",
    stockLabel: "સ્ટોક",
    errorUpdateStock: "સ્ટોક અપડેટ થયો નથી",
    errorUpdatePrice: "ભાવ અપડેટ થયો નથી",
    deleteTitle: "વસ્તુ કાઢી નાખો",
    deleteMsg: (name: string) => `શું તમે ${name} ને દૂર કરવા માંગો છો?`,
    cancel: "રદ કરો",
    delete: "કાઢી નાખો",
  },
  mr: {
    inStock: "स्टॉकमध्ये आहे",
    outOfStock: "संपले आहे",
    lowStock: "कमी स्टॉक",
    priceLabel: "दर",
    stockLabel: "स्टॉक",
    errorUpdateStock: "स्टॉक अपडेट झाला नाही",
    errorUpdatePrice: "दर अपडेट झाला नाही",
    deleteTitle: "माल काढून टाका",
    deleteMsg: (name: string) => `तुम्ही ${name} काढून टाकू इच्छिता का?`,
    cancel: "रद्द करा",
    delete: "काढून टाका",
  },
  te: {
    inStock: "స్టాక్ ఉంది",
    outOfStock: "స్టాక్ లేదు",
    lowStock: "తక్కువ స్టాక్",
    priceLabel: "ధర",
    stockLabel: "స్టాక్",
    errorUpdateStock: "స్టాక్ అప్‌డేట్ కాలేదు",
    errorUpdatePrice: "ధర అప్‌డేట్ కాలేదు",
    deleteTitle: "వస్తువును తొలగించు",
    deleteMsg: (name: string) => `${name}ని తొలగించాలా?`,
    cancel: "రద్దు",
    delete: "తొలగించు",
  },
};

export const LANGUAGE_TEXT_PRODUCT_FORM: any = {
  en: {
    productName: "Product name",
    namePlace: "e.g. Amul Gold Milk 1L",
    sellingPrice: "Selling price",
    openingStock: "Starting stock",
    identification: "Product identification",
    barcode: "Barcode",
    printBarcode: "Print barcode label",
    additionalDetails: "More details",
    category: "Category",
    catPlace: "e.g. Dairy, Grocery",
    sizeVariant: "Size / type",
    sizePlace: "e.g. 500g, Large, XL",
    enableTracking: "Track stock",
    updateProduct: "Update product",
    saveProduct: "Save product",
    requiredFields: "Required details",
    requiredMsg: "Product name and price are required.",
    errorBarcode: "This barcode already exists.",
    errorSave: "Could not save product.",
  },

  hi: {
    productName: "सामान का नाम",
    namePlace: "जैसे: अमूल गोल्ड दूध 1 लीटर",
    sellingPrice: "बेचने का रेट",
    openingStock: "शुरुआती स्टॉक",
    identification: "सामान की पहचान",
    barcode: "बारकोड",
    printBarcode: "बारकोड लेबल प्रिंट करें",
    additionalDetails: "और जानकारी",
    category: "कैटेगरी",
    catPlace: "जैसे: डेयरी, किराना",
    sizeVariant: "साइज़ / प्रकार",
    sizePlace: "जैसे: 500 ग्राम, बड़ा, XL",
    enableTracking: "स्टॉक ट्रैक करें",
    updateProduct: "सामान अपडेट करें",
    saveProduct: "सामान सेव करें",
    requiredFields: "जरूरी जानकारी",
    requiredMsg: "नाम और रेट भरना जरूरी है।",
    errorBarcode: "यह बारकोड पहले से है।",
    errorSave: "सामान सेव नहीं हो पाया।",
  },

  pa: {
    productName: "ਸਾਮਾਨ ਦਾ ਨਾਂ",
    namePlace: "ਜਿਵੇਂ: ਅਮੂਲ ਦੁੱਧ 1 ਲੀਟਰ",
    sellingPrice: "ਵੇਚਣ ਦੀ ਕੀਮਤ",
    openingStock: "ਸ਼ੁਰੂਆਤੀ ਸਟਾਕ",
    identification: "ਸਾਮਾਨ ਦੀ ਪਛਾਣ",
    barcode: "ਬਾਰਕੋਡ",
    printBarcode: "ਬਾਰਕੋਡ ਲੇਬਲ ਪ੍ਰਿੰਟ ਕਰੋ",
    additionalDetails: "ਹੋਰ ਜਾਣਕਾਰੀ",
    category: "ਸ਼੍ਰੇਣੀ",
    catPlace: "ਜਿਵੇਂ: ਡੇਅਰੀ, ਕਰਿਆਨਾ",
    sizeVariant: "ਸਾਈਜ਼ / ਕਿਸਮ",
    sizePlace: "ਜਿਵੇਂ: 500 ਗ੍ਰਾਮ, ਵੱਡਾ, XL",
    enableTracking: "ਸਟਾਕ ਟ੍ਰੈਕ ਕਰੋ",
    updateProduct: "ਸਾਮਾਨ ਅਪਡੇਟ ਕਰੋ",
    saveProduct: "ਸਾਮਾਨ ਸੇਵ ਕਰੋ",
    requiredFields: "ਜ਼ਰੂਰੀ ਜਾਣਕਾਰੀ",
    requiredMsg: "ਨਾਂ ਅਤੇ ਕੀਮਤ ਲਾਜ਼ਮੀ ਹੈ।",
    errorBarcode: "ਇਹ ਬਾਰਕੋਡ ਪਹਿਲਾਂ ਤੋਂ ਹੈ।",
    errorSave: "ਸਾਮਾਨ ਸੇਵ ਨਹੀਂ ਹੋ ਸਕਿਆ।",
  },

  gu: {
    productName: "સામાનનું નામ",
    namePlace: "જેમ કે: અમૂલ દૂધ 1 લીટર",
    sellingPrice: "વેચવાનો ભાવ",
    openingStock: "શરૂઆતનો સ્ટોક",
    identification: "સામાનની ઓળખ",
    barcode: "બારકોડ",
    printBarcode: "બારકોડ લેબલ પ્રિન્ટ કરો",
    additionalDetails: "વધુ માહિતી",
    category: "કેટેગરી",
    catPlace: "જેમ કે: ડેરી, કરિયાણું",
    sizeVariant: "સાઈઝ / પ્રકાર",
    sizePlace: "જેમ કે: 500 ગ્રામ, મોટું, XL",
    enableTracking: "સ્ટોક ટ્રેક કરો",
    updateProduct: "સામાન અપડેટ કરો",
    saveProduct: "સામાન સેવ કરો",
    requiredFields: "જરૂરી માહિતી",
    requiredMsg: "નામ અને ભાવ જરૂરી છે.",
    errorBarcode: "આ બારકોડ પહેલેથી છે.",
    errorSave: "સામાન સેવ થઈ શક્યું નથી.",
  },

  mr: {
    productName: "सामानाचे नाव",
    namePlace: "उदा: अमूल दूध 1 लिटर",
    sellingPrice: "विक्री दर",
    openingStock: "सुरुवातीचा स्टॉक",
    identification: "सामानाची ओळख",
    barcode: "बारकोड",
    printBarcode: "बारकोड लेबल प्रिंट करा",
    additionalDetails: "अधिक माहिती",
    category: "वर्ग",
    catPlace: "उदा: डेअरी, किराणा",
    sizeVariant: "आकार / प्रकार",
    sizePlace: "उदा: 500 ग्रॅम, मोठे, XL",
    enableTracking: "स्टॉक ट्रॅक करा",
    updateProduct: "सामान अपडेट करा",
    saveProduct: "सामान सेव करा",
    requiredFields: "आवश्यक माहिती",
    requiredMsg: "नाव आणि दर आवश्यक आहे.",
    errorBarcode: "हा बारकोड आधीच आहे.",
    errorSave: "सामान सेव होऊ शकले नाही.",
  },

  te: {
    productName: "వస్తువు పేరు",
    namePlace: "ఉదా: అమూల్ పాలు 1 లీటర్",
    sellingPrice: "అమ్మే ధర",
    openingStock: "ప్రారంభ స్టాక్",
    identification: "వస్తువు గుర్తింపు",
    barcode: "బార్కోడ్",
    printBarcode: "బార్కోడ్ లేబుల్ ప్రింట్ చేయండి",
    additionalDetails: "ఇంకా వివరాలు",
    category: "వర్గం",
    catPlace: "ఉదా: డైరీ, కిరాణా",
    sizeVariant: "సైజ్ / రకం",
    sizePlace: "ఉదా: 500 గ్రాములు, పెద్దది, XL",
    enableTracking: "స్టాక్ ట్రాక్ చేయండి",
    updateProduct: "వస్తువు అప్డేట్ చేయండి",
    saveProduct: "వస్తువు సేవ్ చేయండి",
    requiredFields: "అవసరమైన వివరాలు",
    requiredMsg: "పేరు మరియు ధర తప్పనిసరి.",
    errorBarcode: "ఈ బార్కోడ్ ఇప్పటికే ఉంది.",
    errorSave: "వస్తువు సేవ్ కాలేదు.",
  },
};

export const LANGUAGE_TEXT_QUICK_ADD: any = {
  en: {
    title: "Quick Add",
    subtitle: "Add new item",
    scannedBarcode: "Scanned barcode",
    productName: "Product name *",
    namePlace: "e.g. Coca Cola 500ml",
    price: "Price *",
    pricePlace: "₹ 0.00",
    stockQty: "Stock quantity",
    enableTracking: "Track stock",
    moreDetails: "More details",
    lessDetails: "Less details",
    category: "Category",
    size: "Size",
    expiryDate: "Expiry date",
    cancel: "Cancel",
    addProduct: "Add product",
    validationError: "Missing details",
    validationMsg: "Product name and price are required",
    success: "Done!",
    successMsg: "Product added successfully",
    duplicateBarcode: "Barcode already used",
    duplicateMsg: "This barcode already exists in stock",
    error: "Error",
    errorSave: "Could not add product",
  },

  hi: {
    title: "तेज़ एंट्री",
    subtitle: "नया सामान जोड़ें",
    scannedBarcode: "स्कैन किया गया बारकोड",
    productName: "सामान का नाम *",
    namePlace: "जैसे: कोका कोला 500ml",
    price: "रेट *",
    pricePlace: "₹ 0.00",
    stockQty: "स्टॉक मात्रा",
    enableTracking: "स्टॉक ट्रैक करें",
    moreDetails: "और जानकारी",
    lessDetails: "कम जानकारी",
    category: "कैटेगरी",
    size: "साइज़",
    expiryDate: "एक्सपायरी तारीख",
    cancel: "रद्द करें",
    addProduct: "सामान जोड़ें",
    validationError: "जानकारी अधूरी है",
    validationMsg: "नाम और रेट जरूरी है",
    success: "हो गया!",
    successMsg: "सामान सफलतापूर्वक जुड़ गया",
    duplicateBarcode: "बारकोड पहले से है",
    duplicateMsg: "यह बारकोड पहले से स्टॉक में है",
    error: "समस्या",
    errorSave: "सामान नहीं जुड़ पाया",
  },

  pa: {
    title: "ਤੇਜ਼ ਐਂਟਰੀ",
    subtitle: "ਨਵਾਂ ਸਾਮਾਨ ਜੋੜੋ",
    scannedBarcode: "ਸਕੈਨ ਕੀਤਾ ਬਾਰਕੋਡ",
    productName: "ਸਾਮਾਨ ਦਾ ਨਾਂ *",
    namePlace: "ਜਿਵੇਂ: ਕੋਕਾ ਕੋਲਾ 500ml",
    price: "ਕੀਮਤ *",
    pricePlace: "₹ 0.00",
    stockQty: "ਸਟਾਕ ਮਾਤਰਾ",
    enableTracking: "ਸਟਾਕ ਟ੍ਰੈਕ ਕਰੋ",
    moreDetails: "ਹੋਰ ਜਾਣਕਾਰੀ",
    lessDetails: "ਘੱਟ ਜਾਣਕਾਰੀ",
    category: "ਸ਼੍ਰੇਣੀ",
    size: "ਸਾਈਜ਼",
    expiryDate: "ਮਿਆਦ ਦੀ ਤਾਰੀਖ",
    cancel: "ਰੱਦ ਕਰੋ",
    addProduct: "ਸਾਮਾਨ ਜੋੜੋ",
    validationError: "ਜਾਣਕਾਰੀ ਅਧੂਰੀ",
    validationMsg: "ਨਾਂ ਅਤੇ ਕੀਮਤ ਲਾਜ਼ਮੀ ਹੈ",
    success: "ਹੋ ਗਿਆ!",
    successMsg: "ਸਾਮਾਨ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ",
    duplicateBarcode: "ਬਾਰਕੋਡ ਪਹਿਲਾਂ ਤੋਂ ਹੈ",
    duplicateMsg: "ਇਹ ਬਾਰਕੋਡ ਪਹਿਲਾਂ ਹੀ ਸਟਾਕ ਵਿੱਚ ਹੈ",
    error: "ਗਲਤੀ",
    errorSave: "ਸਾਮਾਨ ਨਹੀਂ ਜੋੜਿਆ ਜਾ ਸਕਿਆ",
  },

  gu: {
    title: "ઝડપી એન્ટ્રી",
    subtitle: "નવો સામાન ઉમેરો",
    scannedBarcode: "સ્કેન કરેલો બારકોડ",
    productName: "સામાનનું નામ *",
    namePlace: "જેમ કે: કોકા કોલા 500ml",
    price: "ભાવ *",
    pricePlace: "₹ 0.00",
    stockQty: "સ્ટોક જથ્થો",
    enableTracking: "સ્ટોક ટ્રેક કરો",
    moreDetails: "વધુ માહિતી",
    lessDetails: "ઓછી માહિતી",
    category: "કેટેગરી",
    size: "સાઈઝ",
    expiryDate: "એક્સપાયરી તારીખ",
    cancel: "રદ કરો",
    addProduct: "સામાન ઉમેરો",
    validationError: "માહિતી અધૂરી છે",
    validationMsg: "નામ અને ભાવ જરૂરી છે",
    success: "થઈ ગયું!",
    successMsg: "સામાન સફળતાપૂર્વક ઉમેરાયો",
    duplicateBarcode: "બારકોડ પહેલેથી છે",
    duplicateMsg: "આ બારકોડ પહેલેથી સ્ટોકમાં છે",
    error: "ભૂલ",
    errorSave: "સામાન ઉમેરાઈ શક્યું નથી",
  },

  mr: {
    title: "झटपट नोंद",
    subtitle: "नवीन सामान जोडा",
    scannedBarcode: "स्कॅन केलेला बारकोड",
    productName: "सामानाचे नाव *",
    namePlace: "उदा: कोका कोला 500ml",
    price: "दर *",
    pricePlace: "₹ 0.00",
    stockQty: "स्टॉक प्रमाण",
    enableTracking: "स्टॉक ट्रॅक करा",
    moreDetails: "अधिक माहिती",
    lessDetails: "कमी माहिती",
    category: "वर्ग",
    size: "आकार",
    expiryDate: "एक्सपायरी तारीख",
    cancel: "रद्द करा",
    addProduct: "सामान जोडा",
    validationError: "माहिती अपुरी आहे",
    validationMsg: "नाव आणि दर आवश्यक आहे",
    success: "झाले!",
    successMsg: "सामान यशस्वीपणे जोडले गेले",
    duplicateBarcode: "बारकोड आधीच आहे",
    duplicateMsg: "हा बारकोड आधीच स्टॉकमध्ये आहे",
    error: "चूक",
    errorSave: "सामान जोडता आले नाही",
  },

  te: {
    title: "త్వరిత ఎంట్రీ",
    subtitle: "కొత్త వస్తువు జోడించండి",
    scannedBarcode: "స్కాన్ చేసిన బార్కోడ్",
    productName: "వస్తువు పేరు *",
    namePlace: "ఉదా: కోకా కోలా 500ml",
    price: "ధర *",
    pricePlace: "₹ 0.00",
    stockQty: "స్టాక్ పరిమాణం",
    enableTracking: "స్టాక్ ట్రాక్ చేయండి",
    moreDetails: "ఇంకా వివరాలు",
    lessDetails: "తక్కువ వివరాలు",
    category: "వర్గం",
    size: "సైజ్",
    expiryDate: "గడువు తేదీ",
    cancel: "రద్దు చేయండి",
    addProduct: "వస్తువు జోడించండి",
    validationError: "వివరాలు పూర్తిగా లేవు",
    validationMsg: "పేరు మరియు ధర అవసరం",
    success: "పూర్తయ్యింది!",
    successMsg: "వస్తువు విజయవంతంగా జోడించబడింది",
    duplicateBarcode: "బార్కోడ్ ఇప్పటికే ఉంది",
    duplicateMsg: "ఈ బార్కోడ్ ఇప్పటికే స్టాక్‌లో ఉంది",
    error: "లోపం",
    errorSave: "వస్తువు జోడించబడలేదు",
  },
};


export const LANGUAGE_TEXT_ADD_PRODUCT_MODAL: any = {
  en: {
    title: "Add New Product",
    subtitle: "Fill in details to expand your catalog",
  },
  hi: {
    title: "नया सामान जोड़ें",
    subtitle: "कैटलॉग बढ़ाने के लिए विवरण भरें",
  },
  pa: {
    title: "ਨਵਾਂ ਸਮਾਨ ਜੋੜੋ",
    subtitle: "ਕੈਟਾਲਾਗ ਵਧਾਉਣ ਲਈ ਵੇਰਵੇ ਭਰੋ",
  },
  gu: {
    title: "નવી વસ્તુ ઉમેરો",
    subtitle: "કેટલોગ વધારવા માટે વિગતો ભરો",
  },
  mr: {
    title: "नवीन माल जोडा",
    subtitle: "कॅटलॉग वाढवण्यासाठी तपशील भरा",
  },
  te: {
    title: "కొత్త వస్తువును జోడించు",
    subtitle: "మీ కేటలాగ్‌ను విస్తరించడానికి వివరాలను పూరించండి",
  },
};

export const LANGUAGE_TEXT_EDIT_PRODUCT_MODAL: any = {
  en: {
    title: "Edit Product",
    subtitle: "Update inventory and pricing details",
  },
  hi: {
    title: "सामान बदलें",
    subtitle: "स्टॉक और रेट की जानकारी अपडेट करें",
  },
  pa: {
    title: "ਸਮਾਨ ਸੋਧੋ",
    subtitle: "ਸਟਾਕ ਅਤੇ ਰੇਟ ਦੀ ਜਾਣਕਾਰੀ ਅਪਡੇਟ ਕਰੋ",
  },
  gu: {
    title: "વસ્તુમાં ફેરફાર કરો",
    subtitle: "સ્ટોક અને ભાવની વિગતો અપડેટ કરો",
  },
  mr: {
    title: "माल संपादित करा",
    subtitle: "स्टॉक आणि दराचा तपशील अपडेट करा",
  },
  te: {
    title: "వస్తువును సవరించు",
    subtitle: "స్టాక్ మరియు ధర వివరాలను అప్‌డేట్ చేయండి",
  },
};

export const LANGUAGE_TEXT_INVENTORY_PAGE: any = {
  en: {
    searchPlace: "Search items by name...",
    allItems: "All items",
    lowStock: "Low stock",
    outOfStock: "Out of stock",
    noProducts: "No items found",
    noProductsSub: "Try changing search or filters",
    notice: "Notice",
    alreadyExists: "This product already exists",
  },

  hi: {
    searchPlace: "नाम से सामान खोजें...",
    allItems: "सभी सामान",
    lowStock: "कम स्टॉक",
    outOfStock: "स्टॉक खत्म",
    noProducts: "कोई सामान नहीं मिला",
    noProductsSub: "सर्च या फ़िल्टर बदलकर देखें",
    notice: "सूचना",
    alreadyExists: "यह सामान पहले से मौजूद है",
  },

  pa: {
    searchPlace: "ਨਾਂ ਨਾਲ ਸਾਮਾਨ ਖੋਜੋ...",
    allItems: "ਸਾਰਾ ਸਾਮਾਨ",
    lowStock: "ਘੱਟ ਸਟਾਕ",
    outOfStock: "ਸਟਾਕ ਖਤਮ",
    noProducts: "ਕੋਈ ਸਾਮਾਨ ਨਹੀਂ ਮਿਲਿਆ",
    noProductsSub: "ਸਰਚ ਜਾਂ ਫਿਲਟਰ ਬਦਲ ਕੇ ਵੇਖੋ",
    notice: "ਸੂਚਨਾ",
    alreadyExists: "ਇਹ ਸਾਮਾਨ ਪਹਿਲਾਂ ਤੋਂ ਹੈ",
  },

  gu: {
    searchPlace: "નામથી સામાન શોધો...",
    allItems: "બધો સામાન",
    lowStock: "ઓછો સ્ટોક",
    outOfStock: "સ્ટોક ખતમ",
    noProducts: "કોઈ સામાન મળ્યો નથી",
    noProductsSub: "સર્ચ અથવા ફિલ્ટર બદલીને જુઓ",
    notice: "સૂચના",
    alreadyExists: "આ સામાન પહેલેથી હાજર છે",
  },

  mr: {
    searchPlace: "नावाने सामान शोधा...",
    allItems: "सर्व सामान",
    lowStock: "कमी स्टॉक",
    outOfStock: "स्टॉक संपला",
    noProducts: "कोणतेही सामान सापडले नाही",
    noProductsSub: "सर्च किंवा फिल्टर बदलून पाहा",
    notice: "सूचना",
    alreadyExists: "हे सामान आधीच आहे",
  },

  te: {
    searchPlace: "పేరుతో వస్తువులు వెతకండి...",
    allItems: "అన్ని వస్తువులు",
    lowStock: "స్టాక్ తక్కువ",
    outOfStock: "స్టాక్ అయిపోయింది",
    noProducts: "ఏ వస్తువులు లేవు",
    noProductsSub: "సెర్చ్ లేదా ఫిల్టర్లు మార్చి చూడండి",
    notice: "సూచన",
    alreadyExists: "ఈ వస్తువు ఇప్పటికే ఉంది",
  },
};

export const LANGUAGE_TEXT_BARCODE_SHEET: any = {
  en: {
    headerTitle: "Inventory Barcodes",
    loading: "Loading Inventory...",
    readyTitle: "Ready to Print",
    descStart: "We have generated barcodes for ",
    descEnd: " items in your inventory. The PDF is optimized for A4 sticker sheets.",
    downloadBtn: "Download Barcode Sheet",
    formatInfo: "Format: 3 x 7 Grid (A4)",
    recommendInfo: "Recommended: Laser Printer",
    poweredBy: "Powered by",
  },
  hi: {
    headerTitle: "इन्वेंट्री बारकोड",
    loading: "स्टॉक लोड हो रहा है...",
    readyTitle: "प्रिंट के लिए तैयार",
    descStart: "हमने आपकी इन्वेंट्री के ",
    descEnd: " सामानों के लिए बारकोड बना लिए हैं। यह PDF A4 स्टिकर शीट के लिए तैयार है।",
    downloadBtn: "बारकोड शीट डाउनलोड करें",
    formatInfo: "फॉर्मेट: 3 x 7 ग्रिड (A4)",
    recommendInfo: "सुझाव: लेजर प्रिंटर का उपयोग करें",
    poweredBy: "द्वारा संचालित",
  },
  pa: {
    headerTitle: "ਇਨਵੈਂਟਰੀ ਬਾਰਕੋਡ",
    loading: "ਸਟਾਕ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    readyTitle: "ਪ੍ਰਿੰਟ ਲਈ ਤਿਆਰ",
    descStart: "ਅਸੀਂ ਤੁਹਾਡੀ ਇਨਵੈਂਟਰੀ ਦੇ ",
    descEnd: " ਸਮਾਨ ਲਈ ਬਾਰਕੋਡ ਤਿਆਰ ਕੀਤੇ ਹਨ। ਇਹ PDF A4 ਸਟਿੱਕਰ ਸ਼ੀਟ ਲਈ ਅਨੁਕੂਲ ਹੈ।",
    downloadBtn: "ਬਾਰਕੋਡ ਸ਼ੀਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    formatInfo: "ਫਾਰਮੈਟ: 3 x 7 ਗਰਿੱਡ (A4)",
    recommendInfo: "ਸਿਫਾਰਸ਼: ਲੇਜ਼ਰ ਪ੍ਰਿੰਟਰ",
    poweredBy: "ਦੁਆਰਾ ਸੰਚਾਲਿਤ",
  },
  gu: {
    headerTitle: "ઇન્વેન્ટરી બારકોડ્સ",
    loading: "સ્ટોક લોડ થઈ રહ્યો છે...",
    readyTitle: "પ્રિન્ટ માટે તૈયાર",
    descStart: "અમે તમારી ઇન્વેન્ટરીની ",
    descEnd: " વસ્તુઓ માટે બારકોડ જનરેટ કર્યા છે. PDF A4 સ્ટીકર શીટ્સ માટે ઓપ્ટિમાઇઝ કરેલ છે.",
    downloadBtn: "બારકોડ શીટ ડાઉનલોડ કરો",
    formatInfo: "ફોર્મેટ: 3 x 7 ગ્રીડ (A4)",
    recommendInfo: "ભલામણ કરેલ: લેસર પ્રિન્ટર",
    poweredBy: "દ્વારા સંચાલિત",
  },
  mr: {
    headerTitle: "इन्व्हेंटरी बारकोड",
    loading: "माल लोड होत आहे...",
    readyTitle: "प्रिंटसाठी तयार",
    descStart: "आम्ही तुमच्या इन्व्हेंटरीमधील ",
    descEnd: " वस्तूंसाठी बारकोड तयार केले आहेत. PDF A4 स्टिकर शीटसाठी ऑप्टिमाइझ केलेली आहे.",
    downloadBtn: "बारकोड शीट डाउनलोड करा",
    formatInfo: "फॉर्मेट: 3 x 7 ग्रिड (A4)",
    recommendInfo: "शिफारस केलेले: लेझर प्रिंटर",
    poweredBy: "द्वारे समर्थित",
  },
  te: {
    headerTitle: "ఇన్వెంటరీ బార్‌కోడ్‌లు",
    loading: "స్టాక్ లోడ్ అవుతోంది...",
    readyTitle: "ప్రింట్ చేయడానికి సిద్ధంగా ఉంది",
    descStart: "మేము మీ ఇన్వెంటరీలోని ",
    descEnd: " వస్తువుల కోసం బార్‌కోడ్‌లను రూపొందించాము. PDF A4 స్టిక్కర్ షీట్‌ల కోసం ఆప్టిమైజ్ చేయబడింది.",
    downloadBtn: "బార్‌కోడ్ షీట్‌ను డౌన్‌లోడ్ చేయండి",
    formatInfo: "ఫార్మాట్: 3 x 7 గ్రిడ్ (A4)",
    recommendInfo: "సిఫార్సు చేయబడినది: లేజర్ ప్రింటర్",
    poweredBy: "ద్వారా ఆధారితం",
  }
};