export const LANGUAGE_TEXT_PRINTER: any = {
  en: {
    title: "Printer Setup",
    online: "Printer Online",
    offline: "Printer Offline",
    none: "No Printer Saved",
    statusOnline: "Online",
    statusOffline: "Offline",
    statusNone: "None",
    availableDevices: "Available Devices",
    noPrinters: "No printers found",
    noPrintersSub: "Make sure your printer is powered on and in pairing mode.",
    scanBtn: "Scan for Printers",
    scanAgain: "Scan Again",
    testPrint: "Test Print",
    forgetTitle: "Forget Printer",
    forgetMsg: "This will remove the saved printer. You can reconnect later.",
    forgetBtn: "Forget",
    cancel: "Cancel",
    successTitle: "Success! 🖨️",
    connectedMsg: "connected.",
    readyMsg: "Ready to print!",
    savedOfflineMsg: "Saved, but printer may be off.",
    failTitle: "Connection Failed",
    failMsg: "Make sure printer is powered on and paired in phone settings.",
    loadingInv: "Loading Inventory...",
    unknown: "Unknown Printer",
    onlineLabel: "ONLINE",
    savedLabel: "SAVED (OFFLINE)",
  },

  hi: {
    title: "प्रिंटर सेटअप",
    online: "प्रिंटर ऑनलाइन है",
    offline: "प्रिंटर ऑफलाइन है",
    none: "कोई प्रिंटर सेव नहीं है",
    statusOnline: "ऑनलाइन",
    statusOffline: "ऑफलाइन",
    statusNone: "कोई नहीं",
    availableDevices: "उपलब्ध डिवाइस",
    noPrinters: "कोई प्रिंटर नहीं मिला",
    noPrintersSub: "प्रिंटर चालू करें और पेयरिंग मोड में रखें।",
    scanBtn: "प्रिंटर खोजें",
    scanAgain: "फिर से खोजें",
    testPrint: "टेस्ट प्रिंट",
    forgetTitle: "प्रिंटर हटाएं",
    forgetMsg: "सेव किया गया प्रिंटर हट जाएगा। बाद में फिर जोड़ सकते हैं।",
    forgetBtn: "हटाएं",
    cancel: "रद्द करें",
    successTitle: "सफल! 🖨️",
    connectedMsg: "कनेक्ट हो गया।",
    readyMsg: "प्रिंट के लिए तैयार!",
    savedOfflineMsg: "सेव हो गया, प्रिंटर शायद बंद है।",
    failTitle: "कनेक्शन नहीं हुआ",
    failMsg: "प्रिंटर चालू करें और फोन सेटिंग में पेयर करें।",
    loadingInv: "इन्वेंट्री लोड हो रही है...",
    unknown: "अज्ञात प्रिंटर",
    onlineLabel: "ऑनलाइन",
    savedLabel: "सेव (ऑफलाइन)",
  },

  pa: {
    title: "ਪ੍ਰਿੰਟਰ ਸੈਟਅੱਪ",
    online: "ਪ੍ਰਿੰਟਰ ਆਨਲਾਈਨ ਹੈ",
    offline: "ਪ੍ਰਿੰਟਰ ਆਫਲਾਈਨ ਹੈ",
    none: "ਕੋਈ ਪ੍ਰਿੰਟਰ ਸੇਵ ਨਹੀਂ",
    statusOnline: "ਆਨਲਾਈਨ",
    statusOffline: "ਆਫਲਾਈਨ",
    statusNone: "ਕੋਈ ਨਹੀਂ",
    availableDevices: "ਉਪਲਬਧ ਡਿਵਾਈਸ",
    noPrinters: "ਕੋਈ ਪ੍ਰਿੰਟਰ ਨਹੀਂ ਮਿਲਿਆ",
    noPrintersSub: "ਪ੍ਰਿੰਟਰ ਚਾਲੂ ਕਰੋ ਅਤੇ ਪੇਅਰਿੰਗ ਮੋਡ ਵਿੱਚ ਰੱਖੋ।",
    scanBtn: "ਪ੍ਰਿੰਟਰ ਖੋਜੋ",
    scanAgain: "ਮੁੜ ਖੋਜੋ",
    testPrint: "ਟੈਸਟ ਪ੍ਰਿੰਟ",
    forgetTitle: "ਪ੍ਰਿੰਟਰ ਹਟਾਓ",
    forgetMsg: "ਸੇਵ ਕੀਤਾ ਪ੍ਰਿੰਟਰ ਹਟ ਜਾਵੇਗਾ। ਬਾਅਦ ਵਿੱਚ ਮੁੜ ਜੋੜ ਸਕਦੇ ਹੋ।",
    forgetBtn: "ਹਟਾਓ",
    cancel: "ਰੱਦ ਕਰੋ",
    successTitle: "ਸਫਲ! 🖨️",
    connectedMsg: "ਜੁੜ ਗਿਆ।",
    readyMsg: "ਪ੍ਰਿੰਟ ਲਈ ਤਿਆਰ!",
    savedOfflineMsg: "ਸੇਵ ਹੋ ਗਿਆ, ਪ੍ਰਿੰਟਰ ਸ਼ਾਇਦ ਬੰਦ ਹੈ।",
    failTitle: "ਕਨੈਕਸ਼ਨ ਫੇਲ੍ਹ",
    failMsg: "ਪ੍ਰਿੰਟਰ ਚਾਲੂ ਕਰੋ ਅਤੇ ਫੋਨ ਸੈਟਿੰਗ ਵਿੱਚ ਪੇਅਰ ਕਰੋ।",
    loadingInv: "ਇਨਵੈਂਟਰੀ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...",
    unknown: "ਅਣਜਾਣ ਪ੍ਰਿੰਟਰ",
    onlineLabel: "ਆਨਲਾਈਨ",
    savedLabel: "ਸੇਵ (ਆਫਲਾਈਨ)",
  },

  gu: {
    title: "પ્રિન્ટર સેટઅપ",
    online: "પ્રિન્ટર ઓનલાઈન છે",
    offline: "પ્રિન્ટર ઑફલાઈન છે",
    none: "કોઈ પ્રિન્ટર સેવ નથી",
    statusOnline: "ઓનલાઈન",
    statusOffline: "ઑફલાઈન",
    statusNone: "કોઈ નહીં",
    availableDevices: "ઉપલબ્ધ ડિવાઇસ",
    noPrinters: "કોઈ પ્રિન્ટર મળ્યું નથી",
    noPrintersSub: "પ્રિન્ટર ચાલુ કરો અને પેરિંગ મોડમાં રાખો.",
    scanBtn: "પ્રિન્ટર શોધો",
    scanAgain: "ફરી શોધો",
    testPrint: "ટેસ્ટ પ્રિન્ટ",
    forgetTitle: "પ્રિન્ટર દૂર કરો",
    forgetMsg: "સેવ કરેલું પ્રિન્ટર દૂર થશે. પછી ફરી જોડાઈ શકે છે.",
    forgetBtn: "દૂર કરો",
    cancel: "રદ કરો",
    successTitle: "સફળ! 🖨️",
    connectedMsg: "કનેક્ટ થયું.",
    readyMsg: "પ્રિન્ટ માટે તૈયાર!",
    savedOfflineMsg: "સેવ થયું, પ્રિન્ટર બંધ હોઈ શકે છે.",
    failTitle: "કનેક્શન નિષ્ફળ",
    failMsg: "પ્રિન્ટર ચાલુ કરો અને ફોન સેટિંગમાં પેર કરો.",
    loadingInv: "ઇન્વેન્ટરી લોડ થઈ રહી છે...",
    unknown: "અજાણ્યું પ્રિન્ટર",
    onlineLabel: "ઓનલાઈન",
    savedLabel: "સેવ (ઑફલાઈન)",
  },

  mr: {
    title: "प्रिंटर सेटअप",
    online: "प्रिंटर ऑनलाइन आहे",
    offline: "प्रिंटर ऑफलाइन आहे",
    none: "कोणताही प्रिंटर सेव नाही",
    statusOnline: "ऑनलाइन",
    statusOffline: "ऑफलाइन",
    statusNone: "कोणताही नाही",
    availableDevices: "उपलब्ध डिव्हाइस",
    noPrinters: "कोणताही प्रिंटर सापडला नाही",
    noPrintersSub: "प्रिंटर चालू करा आणि पेअरिंग मोडमध्ये ठेवा.",
    scanBtn: "प्रिंटर शोधा",
    scanAgain: "पुन्हा शोधा",
    testPrint: "टेस्ट प्रिंट",
    forgetTitle: "प्रिंटर काढा",
    forgetMsg: "सेव केलेला प्रिंटर काढला जाईल. नंतर पुन्हा जोडता येईल.",
    forgetBtn: "काढा",
    cancel: "रद्द करा",
    successTitle: "यशस्वी! 🖨️",
    connectedMsg: "कनेक्ट झाला.",
    readyMsg: "प्रिंटसाठी तयार!",
    savedOfflineMsg: "सेव झाला, प्रिंटर कदाचित बंद आहे.",
    failTitle: "कनेक्शन फेल",
    failMsg: "प्रिंटर चालू करा आणि फोन सेटिंगमध्ये पेअर करा.",
    loadingInv: "इन्व्हेंटरी लोड होत आहे...",
    unknown: "अज्ञात प्रिंटर",
    onlineLabel: "ऑनलाइन",
    savedLabel: "सेव (ऑफलाइन)",
  },

  te: {
    title: "ప్రింటర్ సెటప్",
    online: "ప్రింటర్ ఆన్‌లైన్‌లో ఉంది",
    offline: "ప్రింటర్ ఆఫ్‌లైన్‌లో ఉంది",
    none: "ప్రింటర్ సేవ్ కాలేదు",
    statusOnline: "ఆన్‌లైన్",
    statusOffline: "ఆఫ్‌లైన్",
    statusNone: "ఏమీలేదు",
    availableDevices: "లభ్యమైన డివైసులు",
    noPrinters: "ప్రింటర్లు కనబడలేదు",
    noPrintersSub: "ప్రింటర్ ఆన్ చేసి, పెయిరింగ్ మోడ్‌లో ఉంచండి.",
    scanBtn: "ప్రింటర్ వెతకండి",
    scanAgain: "మళ్లీ వెతకండి",
    testPrint: "టెస్ట్ ప్రింట్",
    forgetTitle: "ప్రింటర్ తొలగించండి",
    forgetMsg: "సేవ్ చేసిన ప్రింటర్ తొలగించబడుతుంది. తర్వాత మళ్లీ కనెక్ట్ చేయవచ్చు.",
    forgetBtn: "తొలగించండి",
    cancel: "రద్దు",
    successTitle: "విజయం! 🖨️",
    connectedMsg: "కనెక్ట్ అయ్యింది.",
    readyMsg: "ప్రింట్‌కు సిద్ధం!",
    savedOfflineMsg: "సేవ్ అయింది, ప్రింటర్ ఆఫ్‌లో ఉండవచ్చు.",
    failTitle: "కనెక్షన్ విఫలం",
    failMsg: "ప్రింటర్ ఆన్ చేసి, ఫోన్ సెట్టింగ్స్‌లో పెయిర్ చేయండి.",
    loadingInv: "ఇన్వెంటరీ లోడ్ అవుతోంది...",
    unknown: "తెలియని ప్రింటర్",
    onlineLabel: "ఆన్‌లైన్",
    savedLabel: "సేవ్ (ఆఫ్‌లైన్)",
  },
};
