export const LANGUAGE_TEXT_PROFILE: any = {
  en: {
    title: "Shop Profile",
    subtitle: "Check your shop details",
    identity: "Basic Info",
    bizDetails: "Shop Details",
    location: "Shop Location",
    shopName: "Shop Name",
    ownerName: "Owner Name",
    phone: "Phone Number",
    category: "Category",
    gst: "GST (Optional)",
    upi: "UPI ID",
    gpsAuto: "Auto Location",
    updateBtn: "Save Profile",
    failedLoad: "Could not load profile",
    locUpdated: "Location updated",
    profileSaved: "Profile saved",
    requiredFields: "Please fill required details",
    langSection: "App Language",

    logout: "Logout",
    logoutConfirm: "Are you sure you want to exit?",
    yes: "Yes, Logout",
    cancel: "Cancel",
    updateFailed: "Update failed",
    permDenied: "Location permission denied",
  },

  hi: {
    title: "दुकान प्रोफाइल",
    subtitle: "दुकान की जानकारी जांचें",
    identity: "बुनियादी जानकारी",
    bizDetails: "दुकान विवरण",
    location: "दुकान की लोकेशन",
    shopName: "दुकान का नाम",
    ownerName: "मालिक का नाम",
    phone: "मोबाइल नंबर",
    category: "कैटेगरी",
    gst: "GST (वैकल्पिक)",
    upi: "UPI आईडी",
    gpsAuto: "ऑटो लोकेशन",
    updateBtn: "सेव करें",
    failedLoad: "प्रोफाइल लोड नहीं हुई",
    locUpdated: "लोकेशन अपडेट हो गई",
    profileSaved: "प्रोफाइल सेव हो गई",
    requiredFields: "ज़रूरी जानकारी भरें",
    langSection: "ऐप की भाषा",

    logout: "लॉगआउट",
    logoutConfirm: "क्या आप वाकई बाहर निकलना चाहते हैं?",
    yes: "हाँ, लॉगआउट",
    cancel: "रद्द करें",
    updateFailed: "अपडेट नहीं हो पाया",
    permDenied: "लोकेशन की अनुमति नहीं मिली",
  },

  pa: {
    title: "ਦੁਕਾਨ ਪ੍ਰੋਫਾਈਲ",
    subtitle: "ਦੁਕਾਨ ਦੀ ਜਾਣਕਾਰੀ ਵੇਖੋ",
    identity: "ਮੂਲ ਜਾਣਕਾਰੀ",
    bizDetails: "ਦੁਕਾਨ ਵੇਰਵਾ",
    location: "ਦੁਕਾਨ ਦੀ ਲੋਕੇਸ਼ਨ",
    shopName: "ਦੁਕਾਨ ਦਾ ਨਾਮ",
    ownerName: "ਮਾਲਕ ਦਾ ਨਾਮ",
    phone: "ਮੋਬਾਈਲ ਨੰਬਰ",
    category: "ਸ਼੍ਰੇਣੀ",
    gst: "GST (ਚੋਣਵਾਂ)",
    upi: "UPI ਆਈਡੀ",
    gpsAuto: "ਆਟੋ ਲੋਕੇਸ਼ਨ",
    updateBtn: "ਸੇਵ ਕਰੋ",
    failedLoad: "ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਨਹੀਂ ਹੋਈ",
    locUpdated: "ਲੋਕੇਸ਼ਨ ਅੱਪਡੇਟ ਹੋ ਗਈ",
    profileSaved: "ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਹੋ ਗਈ",
    requiredFields: "ਜ਼ਰੂਰੀ ਜਾਣਕਾਰੀ ਭਰੋ",
    langSection: "ਐਪ ਭਾਸ਼ਾ",

    logout: "ਲਾਗਆਉਟ",
    logoutConfirm: "ਕੀ ਤੁਸੀਂ ਵਾਕਈ ਬਾਹਰ ਜਾਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    yes: "ਹਾਂ, ਲਾਗਆਉਟ",
    cancel: "ਰੱਦ ਕਰੋ",
    updateFailed: "ਅੱਪਡੇਟ ਨਹੀਂ ਹੋਇਆ",
    permDenied: "ਲੋਕੇਸ਼ਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਮਿਲੀ",
  },

  gu: {
    title: "દુકાન પ્રોફાઇલ",
    subtitle: "દુકાનની માહિતી જુઓ",
    identity: "મૂળ માહિતી",
    bizDetails: "દુકાન વિગતો",
    location: "દુકાનનું લોકેશન",
    shopName: "દુકાનનું નામ",
    ownerName: "માલિકનું નામ",
    phone: "મોબાઇલ નંબર",
    category: "શ્રેણી",
    gst: "GST (વૈકલ્પિક)",
    upi: "UPI આઈડી",
    gpsAuto: "ઓટો લોકેશન",
    updateBtn: "સેવ કરો",
    failedLoad: "પ્રોફાઇલ લોડ થઈ નથી",
    locUpdated: "લોકેશન અપડેટ થઈ ગયું",
    profileSaved: "પ્રોફાઇલ સેવ થઈ ગઈ",
    requiredFields: "જરૂરી માહિતી ભરો",
    langSection: "એપ ભાષા",

    logout: "લૉગઆઉટ",
    logoutConfirm: "શું તમે ખરેખર બહાર જવા માંગો છો?",
    yes: "હા, લૉગઆઉટ",
    cancel: "રદ કરો",
    updateFailed: "અપડેટ થયું નથી",
    permDenied: "લોકેશનની પરવાનગી મળી નથી",
  },

  mr: {
    title: "दुकान प्रोफाइल",
    subtitle: "दुकानची माहिती पहा",
    identity: "मूलभूत माहिती",
    bizDetails: "दुकान तपशील",
    location: "दुकानचे ठिकाण",
    shopName: "दुकानचे नाव",
    ownerName: "मालकाचे नाव",
    phone: "मोबाईल नंबर",
    category: "श्रेणी",
    gst: "GST (ऐच्छिक)",
    upi: "UPI आयडी",
    gpsAuto: "ऑटो लोकेशन",
    updateBtn: "सेव करा",
    failedLoad: "प्रोफाइल लोड झाली नाही",
    locUpdated: "लोकेशन अपडेट झाले",
    profileSaved: "प्रोफाइल सेव झाली",
    requiredFields: "आवश्यक माहिती भरा",
    langSection: "अॅप भाषा",

    logout: "लॉगआउट",
    logoutConfirm: "तुम्हाला नक्की बाहेर जायचे आहे का?",
    yes: "हो, लॉगआउट",
    cancel: "रद्द करा",
    updateFailed: "अपडेट झाले नाही",
    permDenied: "लोकेशन परवानगी मिळाली नाही",
  },

  te: {
    title: "దుకాణం ప్రొఫైల్",
    subtitle: "దుకాణ వివరాలు చూడండి",
    identity: "మూల సమాచారం",
    bizDetails: "దుకాణ వివరాలు",
    location: "దుకాణ స్థానం",
    shopName: "దుకాణ పేరు",
    ownerName: "యజమాని పేరు",
    phone: "మొబైల్ నంబర్",
    category: "వర్గం",
    gst: "GST (ఐచ్చికం)",
    upi: "UPI ఐడి",
    gpsAuto: "ఆటో లోకేషన్",
    updateBtn: "సేవ్ చేయండి",
    failedLoad: "ప్రొఫైల్ లోడ్ కాలేదు",
    locUpdated: "లోకేషన్ అప్‌డేట్ అయ్యింది",
    profileSaved: "ప్రొఫైల్ సేవ్ అయ్యింది",
    requiredFields: "అవసరమైన వివరాలు ఇవ్వండి",
    langSection: "యాప్ భాష",

    logout: "లాగ్‌అవుట్",
    logoutConfirm: "మీరు నిజంగా బయటకు వెళ్లాలనుకుంటున్నారా?",
    yes: "అవును, లాగ్‌అవుట్",
    cancel: "రద్దు",
    updateFailed: "అప్‌డేట్ కాలేదు",
    permDenied: "లోకేషన్ అనుమతి లేదు",
  },
};
