export const LANGUAGE_TEXT_BILL_SUMMARY: any = {
  en: {
    discount: "Discount",
    received: "Received",
    subtotal: "Subtotal",
    due: "Due",
    total: "Total Amount",
    cartEmpty: "Cart is empty",
    completeBill: "Make Bill",
  },

  hi: {
    discount: "छूट",
    received: "जमा",
    subtotal: "कुल जोड़",
    due: "बाकी",
    total: "कुल राशि",
    cartEmpty: "कार्ट खाली है",
    completeBill: "बिल निकालें",
  },

  pa: {
    discount: "ਛੂਟ",
    received: "ਜਮਾ",
    subtotal: "ਕੁੱਲ ਜੋੜ",
    due: "ਬਾਕੀ",
    total: "ਕੁੱਲ ਰਕਮ",
    cartEmpty: "ਕਾਰਟ ਖਾਲੀ ਹੈ",
    completeBill: "ਬਿੱਲ ਕੱਢੋ",
  },

  gu: {
    discount: "છૂટ",
    received: "જમા",
    subtotal: "કુલ જોડ",
    due: "બાકી",
    total: "કુલ રકમ",
    cartEmpty: "કાર્ટ ખાલી છે",
    completeBill: "બિલ કાઢો",
  },

  mr: {
    discount: "सूट",
    received: "जमा",
    subtotal: "एकूण जोड",
    due: "बाकी",
    total: "एकूण रक्कम",
    cartEmpty: "कार्ट रिकामी आहे",
    completeBill: "बिल काढा",
  },

  te: {
    discount: "తగ్గింపు",
    received: "జమ",
    subtotal: "మొత్తం",
    due: "బాకీ",
    total: "మొత్తం రకం",
    cartEmpty: "కార్ట్ ఖాళీగా ఉంది",
    completeBill: "బిల్ తీయండి",
  },
};

export const LANGUAGE_TEXT_BILLING: any = {
  en: {
    title: "New Bill",
    terminalActive: "TERMINAL ACTIVE",
    searchProduct: "Search Product",
    alignBarcode: "Align Barcode",
    walkInCustomer: "Walk-in Customer",
    scannerReady: "Scanner Ready",
    searchCustomer: "Search Customer",
    noMobile: "No mobile",
    addNewCustomer: "Add New Customer",
    price: "Price",
  },
  hi: {
    title: "नया बिल",
    terminalActive: "टर्मिनल चालू है",
    searchProduct: "सामान खोजें",
    alignBarcode: "बारकोड मिलाएं",
    walkInCustomer: "अज्ञात ग्राहक",
    scannerReady: "स्कैनर तैयार है",
    searchCustomer: "ग्राहक खोजें",
    noMobile: "नंबर नहीं है",
    addNewCustomer: "नया ग्राहक जोड़ें",
    price: "कीमत",
  },
  pa: {
    title: "ਨਵਾਂ ਬਿੱਲ",
    terminalActive: "ਟਰਮੀਨਲ ਚਾਲੂ ਹੈ",
    searchProduct: "ਸਮਾਨ ਖੋਜੋ",
    alignBarcode: "ਬਾਰਕੋਡ ਮਿਲਾਓ",
    walkInCustomer: "ਆਮ ਗਾਹਕ",
    scannerReady: "ਸਕੈਨਰ ਤਿਆਰ ਹੈ",
    searchCustomer: "ਗਾਹਕ ਖੋਜੋ",
    noMobile: "ਨੰਬਰ ਨਹੀਂ ਹੈ",
    addNewCustomer: "ਨਵਾਂ ਗਾਹਕ ਜੋੜੋ",
    price: "ਕੀਮਤ",
  },
  gu: {
    title: "નવું બિલ",
    terminalActive: "ટર્મિનલ સક્રિય છે",
    searchProduct: "વસ્તુ શોધો",
    alignBarcode: "બારકોડ મેળવો",
    walkInCustomer: "વોક-ઈન ગ્રાહક",
    scannerReady: "સ્કેનર તૈયાર છે",
    searchCustomer: "ગ્રાહક શોધો",
    noMobile: "મોબાઈલ નથી",
    addNewCustomer: "નવો ગ્રાહક ઉમેરો",
    price: "કિંમત",
  },
  mr: {
    title: "नवीन बिल",
    terminalActive: "टर्मिनल चालू आहे",
    searchProduct: "माल शोधा",
    alignBarcode: "बारकोड जुळवा",
    walkInCustomer: "अज्ञात ग्राहक",
    scannerReady: "स्कॅनर तयार आहे",
    searchCustomer: "ग्राहक शोधा",
    noMobile: "नंबर नाही",
    addNewCustomer: "नवीन ग्राहक जोडा",
    price: "किंमत",
  },
  te: {
    title: "కొత్త బిల్లు",
    terminalActive: "టెర్మినల్ సక్రియంగా ఉంది",
    searchProduct: "వస్తువును వెతకండి",
    alignBarcode: "బార్‌కోడ్‌ను అమర్చండి",
    walkInCustomer: "సాధారణ కస్టమర్",
    scannerReady: "స్కానర్ సిద్ధంగా ఉంది",
    searchCustomer: "కస్టమర్‌ను వెతకండి",
    noMobile: "నంబర్ లేదు",
    addNewCustomer: "కొత్త కస్టమర్‌ని జోడించండి",
    price: "ధర",
  }
};


export const LANGUAGE_TEXT_BILL_DETAIL: any = {
  en: {
    loading: "Opening bill…",
    notFound: "Bill not found",
    goBack: "Back",
    title: "Bill Details",
    orderNo: (num: string) => `Bill #${num}`,
    customer: "Customer",
    walkIn: "Walk-in Customer",
    billedItems: "Items",
    itemsCount: (count: number) => `${count} items`,
    unitX: "Qty ×",
    qrTitle: "Payment QR",
    qrInstructions: (amount: string) => `Scan to get ${amount}`,
    errorFetch: "Could not load bill",
    errorShare: "Could not share bill",
    errorPrint: "Could not print bill",
  },

  hi: {
    loading: "बिल खुल रहा है…",
    notFound: "बिल नहीं मिला",
    goBack: "वापस",
    title: "बिल की जानकारी",
    orderNo: (num: string) => `बिल #${num}`,
    customer: "ग्राहक",
    walkIn: "वॉक-इन ग्राहक",
    billedItems: "सामान",
    itemsCount: (count: number) => `${count} आइटम`,
    unitX: "नग ×",
    qrTitle: "पेमेंट QR",
    qrInstructions: (amount: string) => `${amount} पाने के लिए स्कैन करें`,
    errorFetch: "बिल लोड नहीं हुआ",
    errorShare: "बिल शेयर नहीं हुआ",
    errorPrint: "बिल प्रिंट नहीं हुआ",
  },

  pa: {
    loading: "ਬਿੱਲ ਖੁਲ ਰਿਹਾ ਹੈ…",
    notFound: "ਬਿੱਲ ਨਹੀਂ ਮਿਲਿਆ",
    goBack: "ਵਾਪਸ",
    title: "ਬਿੱਲ ਦੀ ਜਾਣਕਾਰੀ",
    orderNo: (num: string) => `ਬਿੱਲ #${num}`,
    customer: "ਗਾਹਕ",
    walkIn: "ਵਾਕ-ਇਨ ਗਾਹਕ",
    billedItems: "ਸਾਮਾਨ",
    itemsCount: (count: number) => `${count} ਆਈਟਮ`,
    unitX: "ਨਗ ×",
    qrTitle: "ਪੇਮੈਂਟ QR",
    qrInstructions: (amount: string) => `${amount} ਲਈ ਸਕੈਨ ਕਰੋ`,
    errorFetch: "ਬਿੱਲ ਲੋਡ ਨਹੀਂ ਹੋਇਆ",
    errorShare: "ਬਿੱਲ ਸ਼ੇਅਰ ਨਹੀਂ ਹੋਇਆ",
    errorPrint: "ਬਿੱਲ ਪ੍ਰਿੰਟ ਨਹੀਂ ਹੋਇਆ",
  },

  gu: {
    loading: "બિલ ખુલ્લું થઈ રહ્યું છે…",
    notFound: "બિલ મળ્યું નથી",
    goBack: "પાછા",
    title: "બિલની માહિતી",
    orderNo: (num: string) => `બિલ #${num}`,
    customer: "ગ્રાહક",
    walkIn: "વોક-ઇન ગ્રાહક",
    billedItems: "સામાન",
    itemsCount: (count: number) => `${count} આઇટમ`,
    unitX: "નગ ×",
    qrTitle: "પેમેન્ટ QR",
    qrInstructions: (amount: string) => `${amount} માટે સ્કેન કરો`,
    errorFetch: "બિલ લોડ થયું નથી",
    errorShare: "બિલ શેર થયું નથી",
    errorPrint: "બિલ પ્રિન્ટ થયું નથી",
  },

  mr: {
    loading: "बिल उघडत आहे…",
    notFound: "बिल सापडले नाही",
    goBack: "मागे",
    title: "बिल माहिती",
    orderNo: (num: string) => `बिल #${num}`,
    customer: "ग्राहक",
    walkIn: "वॉक-इन ग्राहक",
    billedItems: "सामान",
    itemsCount: (count: number) => `${count} वस्तू`,
    unitX: "नग ×",
    qrTitle: "पेमेंट QR",
    qrInstructions: (amount: string) => `${amount} मिळवण्यासाठी स्कॅन करा`,
    errorFetch: "बिल लोड झाले नाही",
    errorShare: "बिल शेअर झाले नाही",
    errorPrint: "बिल प्रिंट झाले नाही",
  },

  te: {
    loading: "బిల్ తెరుచుకుంటోంది…",
    notFound: "బిల్ కనిపించలేదు",
    goBack: "వెనక్కి",
    title: "బిల్ వివరాలు",
    orderNo: (num: string) => `బిల్ #${num}`,
    customer: "గ్రాహకుడు",
    walkIn: "వాక్-ఇన్ కస్టమర్",
    billedItems: "సరుకులు",
    itemsCount: (count: number) => `${count} వస్తువులు`,
    unitX: "నగ ×",
    qrTitle: "పేమెంట్ QR",
    qrInstructions: (amount: string) => `${amount} కోసం స్కాన్ చేయండి`,
    errorFetch: "బిల్ లోడ్ కాలేదు",
    errorShare: "బిల్ షేర్ కాలేదు",
    errorPrint: "బిల్ ప్రింట్ కాలేదు",
  },
};
