/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/barcode-sheet`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `/language`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/PrintTest`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/login-secret`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AnalyticsPinModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/billing`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/ledger`; params?: Router.UnknownInputParams; } | { pathname: `/bills/[billsId]`, params: Router.UnknownInputParams & { billsId: string | number; } } | { pathname: `/ledger/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/barcode-sheet`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/inventory`; params?: Router.UnknownOutputParams; } | { pathname: `/language`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/PrintTest`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-otp`; params?: Router.UnknownOutputParams; } | { pathname: `/login-secret`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/AnalyticsPinModal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/billing`; params?: Router.UnknownOutputParams; } | { pathname: `/history`; params?: Router.UnknownOutputParams; } | { pathname: `/ledger`; params?: Router.UnknownOutputParams; } | { pathname: `/bills/[billsId]`, params: Router.UnknownOutputParams & { billsId: string; } } | { pathname: `/ledger/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/analytics${`?${string}` | `#${string}` | ''}` | `/barcode-sheet${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/inventory${`?${string}` | `#${string}` | ''}` | `/language${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/PrintTest${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/verify-otp${`?${string}` | `#${string}` | ''}` | `/login-secret${`?${string}` | `#${string}` | ''}` | `/../components/AnalyticsPinModal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/billing${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `/ledger${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/barcode-sheet`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `/language`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/PrintTest`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/login-secret`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AnalyticsPinModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/billing`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/ledger`; params?: Router.UnknownInputParams; } | `/bills/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/ledger/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/bills/[billsId]`, params: Router.UnknownInputParams & { billsId: string | number; } } | { pathname: `/ledger/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
